# frozen_string_literal: true

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# See https://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
ENV['RACK_ENV'] = 'test'

require 'simplecov'
SimpleCov.start
require 'rack/test'
require_relative '../app'
require 'rspec'
require 'active_record'

RSpec.configure do |config|
  config.include Rack::Test::Methods
  # rspec-expectations config goes here. You can use an alternate
  # assertion/expectation library such as wrong or the stdlib/minitest
  # assertions if you prefer.
  config.expect_with :rspec do |expectations|
    # This option will default to `true` in RSpec 4. It makes the `description`
    # and `failure_message` of custom matchers include text for helper methods
    # defined using `chain`, e.g.:
    #     be_bigger_than(2).and_smaller_than(4).description
    #     # => "be bigger than 2 and smaller than 4"
    # ...rather than:
    #     # => "be bigger than 2"
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as bogus or mocha) by changing the `mock_with` option here.
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended, and will default to
    # `true` in RSpec 4.
    mocks.verify_partial_doubles = true
  end

  # Configuración de contexto compartido
  config.shared_context_metadata_behavior = :apply_to_host_groups

  # Configuración adicional de RSpec
  # Permite ejecutar ejemplos con `:focus` en lugar de todos los tests
  # config.filter_run_when_matching :focus

  # Persiste el estado de los ejemplos para soportar `--only-failures` y `--next-failure`
  # config.example_status_persistence_file_path = "spec/examples.txt"

  # Modo sin "monkey patching"
  # config.disable_monkey_patching!

  # Habilita advertencias
  # config.warnings = true

  # Configura el formato detallado para un solo archivo de spec
  # config.default_formatter = "doc" if config.files_to_run.one?

  # Imprime los 10 ejemplos más lentos
  # config.profile_examples = 10

  # Ejecuta los tests en orden aleatorio
  # config.order = :random
  # Kernel.srand config.seed

  # Conexión a la base de datos para las pruebas
  config.before(:suite) do
    ActiveRecord::Base.establish_connection(:test)
    ActiveRecord::Migration.maintain_test_schema!
  end

  # Manejo de transacciones
  config.before(:each) do
    ActiveRecord::Base.connection.begin_transaction(joinable: false) # Manejar transacciones por separado
  end

  config.after(:each) do
    ActiveRecord::Base.connection.rollback_transaction
  end
end
def app
  App
end
