# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activerecord'
gem 'database_cleaner'
gem 'rack'
gem 'rack-test'
gem 'rake'
gem 'rspec'
gem 'rubocop'
gem 'simplecov'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-flash'
gem 'sqlite3', '~> 1.4'
